version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqldb
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user_api
      MYSQL_ROOT_HOST: '%'
    volumes:
      - /opt/data:/var/lib/mysql
      - .docker/user_api.sql:/docker-entrypoint-initdb.d/user_api.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3306:3306
    networks:
      - backend
    restart: always

  app:
    image: riqi/komputasi-awan-user
    container_name: user-app
    ports:
      - 4000:4000
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - backend
    restart: always

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

    
    
  